name: Build and Release Apptainer SIF
on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0

      - name: Build SIF from Docker Hub
        run: |
          apptainer pull galba_1.0.11.sif docker://teambraker/galba:1.0.11
          sha256sum galba_1.0.11.sif > galba_1.0.11.sif.sha256

      - name: Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.11
          files: |
            galba_1.0.11.sif
            galba_1.0.11.sif.sha256
